[2024-08-14T19:49:49.834+0900] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-14T19:49:49.867+0900] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: naver-finance-pipeline.soup_result scheduled__2024-08-14T08:00:00+00:00 [queued]>
[2024-08-14T19:49:49.878+0900] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: naver-finance-pipeline.soup_result scheduled__2024-08-14T08:00:00+00:00 [queued]>
[2024-08-14T19:49:49.879+0900] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-14T19:49:49.914+0900] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): soup_result> on 2024-08-14 08:00:00+00:00
[2024-08-14T19:49:49.925+0900] {standard_task_runner.py:64} INFO - Started process 40200 to run task
[2024-08-14T19:49:49.931+0900] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'naver-finance-pipeline', 'soup_result', 'scheduled__2024-08-14T08:00:00+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/soup-pipeline.py', '--cfg-path', '/tmp/tmp112mkwsj']
[2024-08-14T19:49:49.932+0900] {standard_task_runner.py:91} INFO - Job 61: Subtask soup_result
[2024-08-14T19:49:50.036+0900] {task_command.py:426} INFO - Running <TaskInstance: naver-finance-pipeline.soup_result scheduled__2024-08-14T08:00:00+00:00 [running]> on host demo-server
[2024-08-14T19:49:50.176+0900] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='naver-finance-pipeline' AIRFLOW_CTX_TASK_ID='soup_result' AIRFLOW_CTX_EXECUTION_DATE='2024-08-14T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-14T08:00:00+00:00'
[2024-08-14T19:49:50.182+0900] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-14T19:50:22.381+0900] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-14T19:50:22.387+0900] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/urllib3/connection.py", line 196, in _new_conn
    sock = connection.create_connection(
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/urllib3/connection.py", line 615, in connect
    self.sock = sock = self._new_conn()
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/urllib3/connection.py", line 203, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x700465ff0880>: Failed to resolve 'finance.naver.com' ([Errno -3] Temporary failure in name resolution)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='finance.naver.com', port=443): Max retries exceeded with url: /marketindex/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x700465ff0880>: Failed to resolve 'finance.naver.com' ([Errno -3] Temporary failure in name resolution)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ubuntu/airflow/dags/naver_scraper/naver_example.py", line 7, in get_naver_finance
    response = requests.get(URL)
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/ubuntu/miniconda3/envs/airflow-env/lib/python3.8/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='finance.naver.com', port=443): Max retries exceeded with url: /marketindex/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x700465ff0880>: Failed to resolve 'finance.naver.com' ([Errno -3] Temporary failure in name resolution)"))
[2024-08-14T19:50:22.473+0900] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=naver-finance-pipeline, task_id=soup_result, run_id=scheduled__2024-08-14T08:00:00+00:00, execution_date=20240814T080000, start_date=20240814T104949, end_date=20240814T105022
[2024-08-14T19:50:22.535+0900] {standard_task_runner.py:110} ERROR - Failed to execute job 61 for task soup_result (HTTPSConnectionPool(host='finance.naver.com', port=443): Max retries exceeded with url: /marketindex/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x700465ff0880>: Failed to resolve 'finance.naver.com' ([Errno -3] Temporary failure in name resolution)")); 40200)
[2024-08-14T19:50:22.736+0900] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-14T19:50:22.761+0900] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-14T19:50:22.777+0900] {local_task_job_runner.py:222} INFO - ::endgroup::
